includeBuild("build-logic")
includeBuild("markout-plugin")
includeBuild("markout-docusaurus-plugin")
includeBuild("markout")
includeBuild("markout-markdown")
includeBuild("markout-docusaurus")
includeBuild("markout-github-workflows-kt")
include("readme")
